name: medicine_reminder
description: A medicine reminder app for older people
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  flutter_tts: ^3.8.2
  speech_to_text: ^7.0.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  sqflite: ^2.3.2
  path: ^1.9.0
  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
