import 'dart:async';
import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:medicine_reminder/services/rxnorm_service.dart';

import 'rxnorm_service_test.mocks.dart'; // Will be generated by build_runner

@GenerateMocks([http.Client])
void main() {
  late MockClient mockClient;
  late RxNormService service;

  setUp(() {
    mockClient = MockClient();
    service = RxNormService(client: mockClient);
  });

  group('RxNormService - searchRxCuiByName', () {
    test('returns parsed list on match', () async {
      final jsonResponse = {
        'drugGroup': {
          'conceptGroup': [
            {
              'tty': 'SCD',
              'conceptProperties': [
                {'rxcui': '1191', 'name': 'Aspirin 325 MG'}
              ]
            }
          ]
        }
      };

      when(mockClient.get(any)).thenAnswer(
        (_) async => http.Response(jsonEncode(jsonResponse), 200),
      );

      final result = await service.searchRxCuiByName('aspirin');
      expect(result.length, 1);
      expect(result.first['rxcui'], '1191');
      expect(result.first['name'], 'Aspirin 325 MG');
    });

    test('returns empty list when no results found', () async {
      final jsonResponse = {
        'drugGroup': {'conceptGroup': []}
      };

      when(mockClient.get(any)).thenAnswer(
        (_) async => http.Response(jsonEncode(jsonResponse), 200),
      );

      final result = await service.searchRxCuiByName('unknown_medicine');
      expect(result, isEmpty);
    });

    test('excludes items with missing or null rxcui', () async {
      final jsonResponse = {
        'drugGroup': {
          'conceptGroup': [
            {
              'tty': 'SCD',
              'conceptProperties': [
                {'rxcui': '', 'name': 'Aspirin 325 MG'}, // Empty
                {'name': 'Unknown Medicine'}, // Null rxcui
                {'rxcui': '1191', 'name': 'Valid Aspirin'} // Valid
              ]
            }
          ]
        }
      };

      when(mockClient.get(any)).thenAnswer(
        (_) async => http.Response(jsonEncode(jsonResponse), 200),
      );

      final result = await service.searchRxCuiByName('aspirin');
      expect(result.length, 1);
      expect(result.first['rxcui'], '1191');
      expect(result.first['name'], 'Valid Aspirin');
    });

    test('handles 500 error with exactly 3 retries (graceful degradation)',
        () async {
      when(mockClient.get(any)).thenAnswer(
        (_) async => http.Response('Internal Server Error', 500),
      );

      final result = await service.searchRxCuiByName('aspirin');
      expect(result, isEmpty);
      // Verify the client attempted 3 times because of the _maxRetries logic
      verify(mockClient.get(any)).called(3);
    });

    test('fast-fails on TimeoutException without retrying', () async {
      // If the client times out immediately, the service should rethrow fast and gracefully fallback
      when(mockClient.get(any))
          .thenThrow(TimeoutException('Request timed out'));

      final result = await service.searchRxCuiByName('aspirin');
      expect(result, isEmpty);

      // Should only try once and fast-fail
      verify(mockClient.get(any)).called(1);
    });
  });

  group('RxNormService - Cache Behavior', () {
    test('uses memory cache for duplicate searches', () async {
      final jsonResponse = {
        'drugGroup': {
          'conceptGroup': [
            {
              'tty': 'IN',
              'conceptProperties': [
                {'rxcui': '1191', 'name': 'Aspirin'}
              ]
            }
          ]
        }
      };

      when(mockClient.get(any)).thenAnswer(
        (_) async => http.Response(jsonEncode(jsonResponse), 200),
      );

      // First call (hits API)
      final result1 = await service.searchRxCuiByName('aspirin');
      expect(result1.first['rxcui'], '1191');
      verify(mockClient.get(any)).called(1);

      // Second call (hits Cache)
      final result2 = await service.searchRxCuiByName('aspirin');
      expect(result2.first['rxcui'], '1191');
      verifyNoMoreInteractions(mockClient); // No new network call
    });

    test(
        'getInteractions uses sorted cache key to prevent duplicate calls regardless of input order',
        () async {
      final jsonResponse = {
        'fullInteractionTypeGroup': [
          {
            'fullInteractionType': [
              {
                'interactionPair': [
                  {
                    'description': 'Aspirin may interact with Warfarin',
                    'severity': 'high',
                    'interactionConcept': [
                      {
                        'sourceConceptItem': {'name': 'Aspirin'}
                      },
                      {
                        'sourceConceptItem': {'name': 'Warfarin'}
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      };

      when(mockClient.get(any)).thenAnswer(
        (_) async => http.Response(jsonEncode(jsonResponse), 200),
      );

      // Call sorted A, B
      await service.getInteractions(['1191', '11289']);
      verify(mockClient.get(any)).called(1);

      // Call reversed B, A
      await service.getInteractions(['11289', '1191']);

      // Still only 1 call to the API total because the cache key is sorted
      verifyNoMoreInteractions(mockClient);
    });
  });

  group('RxNormService - getInteractions', () {
    test('returns parsed interactions when API succeeds', () async {
      final jsonResponse = {
        'fullInteractionTypeGroup': [
          {
            'fullInteractionType': [
              {
                'interactionPair': [
                  {
                    'description': 'Aspirin may interact with Warfarin',
                    'severity': 'high',
                    'interactionConcept': [
                      {
                        'sourceConceptItem': {'name': 'Aspirin'}
                      },
                      {
                        'sourceConceptItem': {'name': 'Warfarin'}
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      };

      when(mockClient.get(any)).thenAnswer(
        (_) async => http.Response(jsonEncode(jsonResponse), 200),
      );

      final results = await service.getInteractions(['1191', '11289']);
      expect(results.length, 1);
      expect(
          results.first['description'], 'Aspirin may interact with Warfarin');
      expect(results.first['severity'], 'high');
      expect(results.first['drugA'], 'Aspirin');
      expect(results.first['drugB'], 'Warfarin');
    });

    test('returns empty list when no interactions exist', () async {
      when(mockClient.get(any)).thenAnswer(
        (_) async => http.Response('{}', 200),
      );

      final results = await service.getInteractions(['1191', '1234']);
      expect(results, isEmpty);
    });
  });
}
